### ISSUE TITLE
C6 documentation

### ISSUE THREAD

**Issue by cyring** [r4m0n/ZenStates-Linux#3]
Hello,
To enhance my C-States software (_CoreFreq_), could you please provide the bit fields of the msr:
```0xC0010292```  
```0xC0010296```  
Regards,
CyrIng

**Comment by paulmenzel** [comment]
Did you find the documentation for the two MSRs?

**Comment by cyring** [comment]
No specs from manufacturer found but misc `0xC0010292 , 0xC0010296` traces [here](https://pastebin.com/Jn0PZgmp) ; [Hygon](https://www.virtualbox.org/svn/vbox/trunk/src/VBox/VMM/VMMR3/cpus/Hygon_C86_7185_32_core.h) and [here](https://bugzilla.kernel.org/show_bug.cgi?id=196683)
